FROM openjdk:11

WORKDIR /app

ADD ./target/authentication-service-0.0.1-SNAPSHOT.jar /app/authentication-service-0.0.1-SNAPSHOT.jar



ENTRYPOINT ["java","-jar", "authentication-service-0.0.1-SNAPSHOT.jar"]
